services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: student-management-system-db-server
    networks:
      - student-management-system-network
    ports:
      - "5432:5432"
    volumes:
      - psqldata:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    container_name: student-management-system-api
    networks:
      - student-management-system-network
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  psqldata:

networks:
  student-management-system-network:
    driver: bridge
