"""alter table test add column text

Revision ID: 33783416d54c
Revises: 2a377fb74a24
Create Date: 2024-08-11 21:41:56.561537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33783416d54c'
down_revision: Union[str, None] = '2a377fb74a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'text')
    # ### end Alembic commands ###
